[package]
name = "lodepng"
version = "0.1.0"
authors = ["Peter Atashian <retep998@gmail.com>"]
links = "lodepng"
build = "build.rs"

[dependencies]
image = { version = "0.17", default-features = false }
libc = "0.2"

[build-dependencies]
cc = "1.0"
